### ISSUE TITLE
Idea: Add a Promise API to the library

### ISSUE THREAD

**Issue by ajaymathur** [AbregaInc/har-cleaner#2]
This library could be a good use case to export another promise API where all the actions are async. The API may look like:

```js
import { sanitizeHar } from "har-cleaner/promise";

scrubbedHar = await sanitizeHar(harObject, {
    scrubAllCookies: options.scrubAllCookies,
    ...otherOptions
});
```

This should improve the performance of the library further as we can run all the different sanitizations in parallel. 

Please let me know what you think of it.

**Comment by bberenberg** [comment]
Is the idea that a consumer of the library could call parallel cleaning operations? If yes, why make the call here async vs the scrubbing function internal to the consumer codebase?

Is there a use case in mind for this? 

Do you have any kind of performance benchmark to support the argument that it would be helpful?

Given the [memory pressure of loading HAR files into memory](https://stackoverflow.com/questions/44916333/why-is-a-javascript-object-literal-in-memory-so-much-bigger-than-its-text-file-s) I am not sure if the idea of loading more of these into memory in parallel is a good architecture the library should encourage.

**Comment by ajaymathur** [comment]
Hey @bberenberg, I was thinking of more like operation being parallel within the library. But now only I realized that all the operations are on the same object so I think we cannot parallelize them. Thanks for the questions that helped me think over it. cheers.

*I am closing the issue. 👍
